import { createClient } from "@/app/utils/supabase/server";
import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { Profiles } from "@prisma/client";

const genAI = new GoogleGenAI({});

async function generateInternshipWeeksWithGemini(userProfile: Profiles) {
  const prompt = `
    Based on the following user profile, generate a 12-week internship roadmap. Each week should include one project to complete, one problem to solve, and the main topic(s) to be learned. The difficulty should gradually increase, considering the user's domain and profile. The projects and problems should be creative, based on the latest technologies, and aligned with the user's interests and goals.

    User Profile:
    - ID: ${userProfile.id}
    - Name: ${userProfile.name}
    - Username: ${userProfile.username}
    - Domain: ${userProfile.domain || "Web Development"}
    - College Name: ${userProfile.college_name || "Not specified"}
    - Year of Study: ${userProfile.year_of_study || "Graduate"}
    - Primary Field: ${userProfile.primary_field || "Computer Science"}
    - Comfort Level: ${userProfile.comfort_level || "Advanced"}
    - Preferred Languages: ${
      userProfile.preferred_langs.join(", ") || "Python, JavaScript"
    }
    - Platform Experience: ${userProfile.platform_exp || "No"}
    - Main Goal: ${
      userProfile.main_goal.join(", ") ||
      "To improve my coding skills, To earn certificates and LORs"
    }
    - Challenge Preference: ${
      userProfile.challenge_pref.join(", ") ||
      "Algorithmic problems, Web development tasks, Real-world projects, Problem-solving contests"
    }
    - Motivation: ${
      userProfile.motivation.join(", ") ||
      "Learning new skills, Building portfolio-worthy projects"
    }
    - Time Dedication: ${userProfile.time_dedication || "More than 10 hours"}
    - Internship Interest: ${userProfile.internship_interest || "Maybe later"}
    - Role Interests: ${
      userProfile.role_interest.join(", ") ||
      "Software Development, Web Development"
    }
    - Project Preference: ${
      userProfile.project_pref || "Collaborative / Team-based"
    }
    - Playstyle: ${userProfile.playstyle || "The Explorer (learns everything)"}
    - First Badge: ${userProfile.first_badge || "Project Pioneer"}
    - Internship Enrolled: ${userProfile.internship_enrolled}

    The output MUST be a valid JSON array named "internship" containing exactly 12 objects. Do not include any text, markdown, or explanations outside of the JSON array itself.
    Each object in the array must follow this exact structure:
    {
      "week": "Week [number]",
      "topic": "Main topic(s) to learn this week",
      "project": {
        "title": "Project Title",
        "description": "A detailed project description (3-5 sentences), including key technologies or concepts to apply."
      },
      "problem": {
        "title": "Problem Title",
        "description": "A detailed problem description (2-4 sentences), outlining the task and expected outcome."
      }
    }
  `;

  try {
    const response = await genAI.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    const text = response.text;
    if (!text) {
      throw new Error("No text generated by the model.");
    }

    const cleanedText = text
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    const generatedInternship = JSON.parse(cleanedText);

    return generatedInternship.internship as {
      week: string;
      topic: string;
      project: {
        title: string;
        description: string;
      };
      problem: {
        title: string;
        description: string;
      };
    }[];
  } catch (error) {
    console.error("Error generating internship weeks with Gemini:", error);
    throw new Error("Failed to generate internship weeks from AI.");
  }
}

export async function GET() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const existingInternshipWeeks = await prisma.internshipWeek.findMany({
      where: {
        userId: user.id,
      },
      orderBy: {
        weekNumber: "asc",
      },
    });

    if (existingInternshipWeeks.length > 0) {
      const formattedWeeks = existingInternshipWeeks.map((week) => ({
        week: `Week ${week.weekNumber}`,
        topic: week.topic,
        project: {
          title: week.projectTitle,
          description: week.projectDescription,
        },
        problem: {
          title: week.problemTitle,
          description: week.problemDescription,
        },
      }));
      return NextResponse.json({ internship: formattedWeeks }, { status: 200 });
    }

    const userProfile = await prisma.profiles.findUnique({
      where: {
        id: user.id,
      },
    });

    if (!userProfile) {
      return NextResponse.json(
        { message: "User profile not found, cannot generate projects." },
        { status: 404 }
      );
    }

    const generatedInternshipWeeks = await generateInternshipWeeksWithGemini(
      userProfile
    );

    const weeksToSave = generatedInternshipWeeks.map((weekData, index) => ({
      userId: user.id,
      weekNumber: index + 1,
      topic: weekData.topic,
      projectTitle: weekData.project.title,
      projectDescription: weekData.project.description,
      problemTitle: weekData.problem.title,
      problemDescription: weekData.problem.description,
    }));

    await prisma.internshipWeek.createMany({
      data: weeksToSave,
      skipDuplicates: true,
    });

    const savedInternshipWeeks = await prisma.internshipWeek.findMany({
      where: {
        userId: user.id,
      },
      orderBy: {
        weekNumber: "asc",
      },
    });

    const formattedSavedWeeks = savedInternshipWeeks.map((week) => ({
      week: `Week ${week.weekNumber}`,
      topic: week.topic,
      project: {
        title: week.projectTitle,
        description: week.projectDescription,
      },
      problem: {
        title: week.problemTitle,
        description: week.problemDescription,
      },
    }));

    return NextResponse.json(
      { internship: formattedSavedWeeks },
      { status: 201 }
    );
  } catch (error) {
    console.error("API Error:", error);
    return NextResponse.json(
      { message: "An internal server error occurred." },
      { status: 500 }
    );
  }
}
