import { createClient } from "@/app/utils/supabase/server";
import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { Profiles } from "@prisma/client";

const genAI = new GoogleGenAI({ apiKey: process.env.GOOGLE_API_KEY });

interface GeneratedWeek {
  weekNumber: number;
  title: string;
  description: string;
  topics: string[];
}

async function generateInternshipWeeksOnly(
  userProfile: Profiles
): Promise<GeneratedWeek[]> {
  const prompt = `
    Based on the following user profile, generate a high-level 12-week internship roadmap.
    
    User Profile:
    - Domain: ${userProfile.domain || "Web Development"}
    - Current Skill Level: ${userProfile.comfort_level || "Intermediate"}
    - Tech Stack: ${userProfile.preferred_langs.join(", ") || "JavaScript"}
    - Goal: ${userProfile.main_goal.join(", ") || "Improve skills"}

    The output MUST be a valid JSON array named "weeks" containing exactly 12 objects. 
    Do not include markdown formatting, explanations, or code blocks. Just the raw JSON.

    Each object must follow this schema exactly:
    {
      "weekNumber": number (1-12),
      "title": "A clear, professional title for the week (e.g., 'Advanced State Management')",
      "description": "A brief overview (2 sentences) of the learning focus for this week.",
      "topics": ["Topic 1", "Topic 2", "Topic 3"]
    }
  `;

  try {
    const response = await genAI.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    const text = response.text;

    if (!text) {
      throw new Error("No text generated by the model.");
    }

    const cleanedText = text
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    const parsedData = JSON.parse(cleanedText);

    if (!Array.isArray(parsedData.weeks) || parsedData.weeks.length === 0) {
      throw new Error("Invalid JSON structure received from AI");
    }

    return parsedData.weeks as GeneratedWeek[];
  } catch (error) {
    console.error("Error generating internship weeks:", error);
    throw new Error("Failed to generate internship weeks from AI.");
  }
}

export async function GET() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const existingWeeks = await prisma.internshipWeek.findMany({
      where: {
        userId: user.id,
      },
      orderBy: {
        weekNumber: "asc",
      },
    });

    if (existingWeeks.length > 0) {
      return NextResponse.json({ internship: existingWeeks }, { status: 200 });
    }

    const userProfile = await prisma.profiles.findUnique({
      where: { id: user.id },
    });

    if (!userProfile) {
      return NextResponse.json(
        { message: "User profile not found." },
        { status: 404 }
      );
    }

    const generatedWeeks = await generateInternshipWeeksOnly(userProfile);

    const weeksToCreate = generatedWeeks.map((week) => ({
      userId: user.id,
      weekNumber: week.weekNumber,
      title: week.title,
      description: week.description,
      topics: week.topics,
    }));

    await prisma.internshipWeek.createMany({
      data: weeksToCreate,
      skipDuplicates: true,
    });

    const savedWeeks = await prisma.internshipWeek.findMany({
      where: { userId: user.id },
      orderBy: { weekNumber: "asc" },
    });

    return NextResponse.json({ internship: savedWeeks }, { status: 201 });
  } catch (error) {
    console.error("API Error:", error);
    return NextResponse.json(
      { message: "An internal server error occurred." },
      { status: 500 }
    );
  }
}
