import { createClient } from "@/app/utils/supabase/server";
import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import { Profiles } from "@prisma/client";

const genAI = new GoogleGenAI({});

async function generateProjectsWithGemini(userProfile: Profiles) {
  const prompt = `
    Based on the following user profile, generate 4 distinct and creative internship project ideas based on latest technologies with brief case study.
    The user is interested in:
    - Domain: ${userProfile.domain || "Not specified"}
    - Preferred Languages: ${
      userProfile.preferred_langs.join(", ") || "Not specified"
    }
    - Primary Field: ${userProfile.primary_field || "Not specified"}
    - Role Interests: ${userProfile.role_interest.join(", ") || "Not specified"}

    The output MUST be a valid JSON array containing exactly 4 objects. Do not include any text, markdown, or explanations outside of the JSON array itself.
    Each object in the array must follow this exact structure:
    {
      "title": "Project Title",
      "description": "A detailed project description (2-3 sentences).",
      "caseStudy": "A brief case study or real-world application of the project.",
      "techStack": ["Technology1", "Technology2", "Technology3"],
      "maxTime": "Estimated maximum time to complete (e.g., '2 Weeks', '1 Month')"
    }
  `;

  try {
    const response = await genAI.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    const text = response.text;
    if (!text) {
      throw new Error("No text generated by the model.");
    }

    const cleanedText = text
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    const generatedProjects = JSON.parse(cleanedText);

    return generatedProjects as {
      title: string;
      description: string;
      caseStudy: string;
      techStack: string[];
      maxTime: string;
    }[];
  } catch (error) {
    console.error("Error generating projects with Gemini:", error);
    throw new Error("Failed to generate projects from AI.");
  }
}

export async function GET() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const existingProjects = await prisma.internshipProject.findMany({
      where: {
        userId: user.id,
      },
    });

    if (existingProjects.length > 0) {
      const projectsWithTechStack = existingProjects.map(project => ({
        title: project.title,
        description: project.description,
        caseStudy: project.caseStudy,
        techStack: project.techStack || [],
        maxTime: project.maxTime,
      }));
      return NextResponse.json(projectsWithTechStack, { status: 200 });
    }

    const userProfile = await prisma.profiles.findUnique({
      where: {
        id: user.id,
      },
    });

    if (!userProfile) {
      return NextResponse.json(
        { message: "User profile not found, cannot generate projects." },
        { status: 404 }
      );
    }

    const generatedProjects = await generateProjectsWithGemini(userProfile);

    const projectsToSave = generatedProjects.map((project) => ({
      title: project.title,
      description: project.description,
      caseStudy: project.caseStudy,
      techStack: project.techStack,
      maxTime: project.maxTime,
      userId: user.id,
    }));

    await prisma.internshipProject.createMany({
      data: projectsToSave,
    });

    return NextResponse.json(generatedProjects, { status: 201 });
  } catch (error) {
    console.error("API Error:", error);
    return NextResponse.json(
      { message: "An internal server error occurred." },
      { status: 500 }
    );
  }
}